<a href="https://colab.research.google.com/github/Yashmitha18/AIML-Project/blob/main/DAY7.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import seaborn as sns
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split

In [2]:
df = pd.read_csv('https://talentcocomedia.s3.amazonaws.com/ml-assets/heart-disease.csv')

In [3]:
y = df['target']

In [4]:
x = df.drop('target',axis=1)

In [5]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3)

**Logistic Regression - GridSearchCV**

In [6]:
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import accuracy_score

lr_model = LogisticRegression(penalty='l2')

val = list(np.arange(1, 10, 1))

parameters = {'solver':('newton-cg', 'liblinear', 'sag', 'saga'), 'C':val}

clf_lr = GridSearchCV(lr_model, parameters)
clf_lr.fit(x_train, y_train)
     

/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means the coef_ did not converge
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/linear_model/_sag.py:350: ConvergenceWarning: The max_iter was reached which means 

GridSearchCV(estimator=LogisticRegression(),
             param_grid={'C': [1, 2, 3, 4, 5, 6, 7, 8, 9],
                         'solver': ('newton-cg', 'liblinear', 'sag', 'saga')})

In [7]:
print(clf_lr.best_params_)

{'C': 1, 'solver': 'liblinear'}


In [8]:
test_pred = clf_lr.predict(x_test)

In [9]:
acc_lr_gs = accuracy_score(test_pred,y_test)
acc_lr_gs

0.8021978021978022

Previously we had got an accuracy of 75.82% but now it is improved to 80.21%

**KNeighborsClassifier - GridSearchCV**

In [10]:
from sklearn.neighbors import KNeighborsClassifier

neigh = KNeighborsClassifier()

val = list(np.arange(1,30, 1))

parameters = {'n_neighbors':val}

clf_knn = GridSearchCV(neigh, parameters)
clf_knn.fit(x_train, y_train)

GridSearchCV(estimator=KNeighborsClassifier(),
             param_grid={'n_neighbors': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12,
                                         13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
                                         23, 24, 25, 26, 27, 28, 29]})

In [11]:
print(clf_knn.best_params_)

{'n_neighbors': 19}


In [12]:
test_pred_knn = clf_knn.predict(x_test)

In [13]:
accuracy_knn_gs = accuracy_score(test_pred_knn, y_test)
accuracy_knn_gs

0.6373626373626373

Previously we had got an accuracy score of 59.34% but now it is improved to 63.73%

**DecisionTreeClassifier - GridSearchCV**

In [14]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import train_test_split
from sklearn import metrics

In [15]:
clf = DecisionTreeClassifier(random_state=1024)

param_grid = {
              'max_features': ['auto', 'sqrt', 'log2'],
              'ccp_alpha': [0.1, .01, .001],
              'max_depth' : np.arange(5,10,1),
              'criterion' :['gini', 'entropy']
             }

clf_dtc = GridSearchCV(clf, param_grid=param_grid, cv=5, verbose=True)

clf_dtc.fit(x_train, y_train)

Fitting 5 folds for each of 90 candidates, totalling 450 fits


/usr/local/lib/python3.9/dist-packages/sklearn/tree/_classes.py:269: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'`.
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/tree/_classes.py:269: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'`.
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/tree/_classes.py:269: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'`.
  warnings.warn(
/usr/local/lib/python3.9/dist-packages/sklearn/tree/_classes.py:269: FutureWarning: `max_features='auto'` has been deprecated in 1.1 and will be removed in 1.3. To keep the past behaviour, explicitly set `max_features='sqrt'`.
  warnings.warn(
/usr/local/lib/python3.9

GridSearchCV(cv=5, estimator=DecisionTreeClassifier(random_state=1024),
             param_grid={'ccp_alpha': [0.1, 0.01, 0.001],
                         'criterion': ['gini', 'entropy'],
                         'max_depth': array([5, 6, 7, 8, 9]),
                         'max_features': ['auto', 'sqrt', 'log2']},
             verbose=True)

In [16]:
print(clf_dtc.best_params_)

{'ccp_alpha': 0.001, 'criterion': 'gini', 'max_depth': 6, 'max_features': 'auto'}


In [17]:
test_pred_dtc = clf_dtc.predict(x_test)

In [18]:
accuracy_dtc_gs = metrics.accuracy_score(y_test, test_pred_dtc)
accuracy_dtc_gs

0.6373626373626373

**CONFUSION MATRIX**

Since we got a accuracy of 80% using Linear-Regression, we use its predicted accuracy to find the confusion matrix

**Logistic Regression**

In [19]:
from sklearn.metrics import confusion_matrix
confusion_matrix(test_pred,y_test)

array([[37,  5],
       [13, 36]])

In [20]:
from sklearn.metrics import classification_report

print(classification_report(y_test,test_pred))

              precision    recall  f1-score   support

           0       0.88      0.74      0.80        50
           1       0.73      0.88      0.80        41

    accuracy                           0.80        91
   macro avg       0.81      0.81      0.80        91
weighted avg       0.82      0.80      0.80        91



**KNeighborsClassifier**

In [21]:
confusion_matrix(test_pred_knn,y_test)

array([[24,  7],
       [26, 34]])

In [22]:
print(classification_report(y_test,test_pred_knn))

              precision    recall  f1-score   support

           0       0.77      0.48      0.59        50
           1       0.57      0.83      0.67        41

    accuracy                           0.64        91
   macro avg       0.67      0.65      0.63        91
weighted avg       0.68      0.64      0.63        91



**DecisionTreeClassifier**

In [23]:
confusion_matrix(test_pred_dtc,y_test)

array([[28, 11],
       [22, 30]])

In [24]:
print(classification_report(y_test,test_pred_dtc))

              precision    recall  f1-score   support

           0       0.72      0.56      0.63        50
           1       0.58      0.73      0.65        41

    accuracy                           0.64        91
   macro avg       0.65      0.65      0.64        91
weighted avg       0.65      0.64      0.64        91



From the above comparisions we come to a conclusion that DecisionTreeClassifier provides a better Recall along with accuracy when compared to other Modals